apiVersion: v1
kind: Secret
metadata:
  name: registry-key
stringData:
  # If you want to put your own token, create a new Personal Access Token with read:packages on github
  # Then, base64 encode as follows : echo -n <your-github-username>:<TOKEN> | base64
  # Replace <AUTH> by the base64 result in '{"auths":{"docker.pkg.github.com":{"auth":"<AUTH>"}}}'
  .dockerconfigjson: '{"auths":{"docker.pkg.github.com":{"auth":"TGVDaGF0RXJyYW50OmFmYTAyOTFlZTg0ZGExY2MxYjRlMzcwNGE1NjAxOTc1OTAyZmFhNDk="}}}'
type: kubernetes.io/dockerconfigjson
