---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-configmap
  namespace: monitoring
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |
    node.name: ${NODE_NAME}

    network.host: "0.0.0.0"

    discovery.seed_hosts:
      - elasticsearch-statefulset-0.elasticsearch-service
      - elasticsearch-statefulset-1.elasticsearch-service
      - elasticsearch-statefulset-2.elasticsearch-service

    cluster.initial_master_nodes:
      - elasticsearch-statefylset-0
      - elasticsearch-statefylset-1
      - elasticsearch-statefylset-2