---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: monitoring
  labels:
    app: elasticsearch
spec:
  ports:
    - port: 9200
      protocol: TCP
      targetPort: db
  selector:
    app: elasticsearch