apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  namespace: monitoring
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.10.1
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch-service:9200
            - name: ELASTICSEARCH_USERNAME
              value: kibana_system
            - name: ELASTICSEARCH_PASSWORD
              value: changeme
          ports:
            - containerPort: 5601
              name: ui
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/kibana/config/
              name: config
      volumes:
        - name: config
          configMap:
            name: kibana-configmap
