---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  labels:
    lechaterrant.com/app: traefik
    lechaterrant.com/stack: traefik
data:
  users: YWRtaW46JGFwcjEkaFAvbGpXMmEkaS42Tkh5TEFQRWRvVGxLcU5DcFlRLwoK
